default_stages: [commit]

repos:
    - repo: https://github.com/charliermarsh/ruff-pre-commit
      rev: v0.0.292
      hooks:
          - id: ruff
            args:
                [
                    "--extend-select",
                    "F401",
                    "--extend-select",
                    "F841",
                    "--extend-select",
                    "B007",
                    "--fix",
                ]

    - repo: https://github.com/psf/black
      rev: 23.9.1
      hooks:
          - id: black
