# Use Python 3.10 slim as the base image
FROM python:3.10-bullseye
RUN apt-get install -y git

# Set the working directory to /app
WORKDIR /app

# Dev experience
COPY requirements-dev.txt ./
RUN pip install -r requirements-dev.txt

## Run static-type-checks to initialise the cache
COPY Makefile ./
RUN make type-check

## Initialise pre-commit
### Remove the .git repo afterwards, since the dev container bind-mounts the development repo
COPY .pre-commit-config.yaml ./
RUN git init . && make lint

# App install
## Each on their own line to have them be their own layers, optimising caching
COPY requirements.txt .
RUN pip install -r requirements.txt

COPY requirements-test.txt .
RUN pip install -r requirements-test.txt

COPY pyproject.toml ./

COPY . /app
RUN pip install -e .