FROM python:3.11-bullseye

# Update default packages
RUN apt-get -qq update

# Get Ubuntu packages
RUN apt-get install -y -q \
    build-essential \
    curl \
    cmake

# NOTE: no need to run update again at this point
# RUN apt-get update

# Get Rust; NOTE: using sh for better compatibility with other base images
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y

# Add .cargo/bin to PATH
ENV PATH="/root/.cargo/bin:${PATH}"

# Set the working directory to /app
WORKDIR /app

# Dev experience
COPY makefile ./
COPY pyproject.toml ./
RUN make install

# Install the app
COPY . /app
RUN pip install -e .
