site_name: Danish Foundation Models
docs_dir: "docs/"
repo_url: https://github.com/centre-for-humanities-computing/danish-foundation-models
watch: [docs/]
edit_uri: "blob/main/docs/"
theme:
  name: material
  favicon: _static/icon.png
  logo: _static/icon.png
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - toc.follow
    - pymdownx.caret
    - pymdownx.tilde
    - content.action.edit
  palette:
    primary: white
    accent: light blue
    # automatic dark mode is

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences

copyright: Copyright &copy; 2023 Danish Foundation Models Project

nav:
  - About: index.md
  - Models: models.md
  - Datasets:
      - DCC: dcc.md
      - Datasheets:
          - DaNews: datasheets/danews.md
          - HopeTwitter: datasheets/hopetwitter.md
          - NAT: datasheets/netarkivet_text.md
          - DaRadio: datasheets/daradio.md
  - Blog: blog

plugins:
  - mkdocs-jupyter
  - search
  - blog

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/centre-for-humanities-computing/danish-foundation-models
