from typing import Dict, List
from dfm.description import MatchCounter

# Terms for religions are:
# * The person-noun singular (e.g. "kristen") and conjugated
# * The adjective (e.g. kristent)
# * The religion-noun singular (e.g. "kristendom") and conjugated
religion_labelled_match_patterns = {
    {"muslim": ["muslim", "muslimen", "muslimer", "muslimerne", "muslimsk", "islam"]},
    {
        "christian": [
            "kristen",
            "kristne",
            "kristent",
            "kristendom",
            "kristendomme",
            "kristendommen",
            "kristendommene",
        ]
    },
    {
        "jew": [
            "jøde",
            "jøden",
            "jøder",
            "jøderne",
            "jødisk",
            "jødedom",
            "jødedommen",
            "jødedomme",
            "jødedommene",
        ]
    },
    {
        "buddhist": [
            "buddhist",
            "buddhisten",
            "buddhister",
            "buddhisterne",
            "buddhistisk",
            "buddhisme",
            "buddhismen",
            "buddhismer",
            "buddhismerne",
        ]
    },
    {
        "hindu": [
            "hinduist",
            "hinduisten",
            "hinduister",
            "hinduisterne",
            "hindu",
            "hinduen",
            "hinduer",
            "hinduerne",
            "hinduistisk",
            "hinduisme",
            "hinduismen",
            "hinduismer",
            "hinduismerne",
        ]
    },
    {
        "atheist": [
            "atheist",
            "atheisten",
            "atheister",
            "atheisterne",
            "atheistisk",
            "atheisme",
            "ahteismen",
            "atheismer",
            "atheismerne",
        ]
    },
}


def get_religion_patterns():
    return MatchCounter.list_of_labelled_term_lists_to_spacy_match_patterns(
        religion_labelled_match_patterns
    )


occupation_pattern_list = set(
    [
        "revisor",
        "revisoren",
        "revisorer",
        "revisorerne",
        "administrator",
        "administratoren",
        "administratorer",
        "administratorerne",
        "analytiker",
        "analytikeren",
        "analytikere",
        "analytikerne",
        "arkitekt",
        "arkitekten",
        "arkitekter",
        "arkitekterne",
        "assistent",
        "assistenten",
        "assistenter",
        "assistenterne",
        "bager",
        "bageren",
        "bagere",
        "bagerne",
        "bartender",
        "bartenderen",
        "bartendere",
        "bartenderne",
        "ejendomsmægler",
        "ejendomsmægleren",
        "ejendomsmæglere",
        "ejendomsmæglerne" "tømrer",
        "tømreren",
        "tømrere",
        "tømrerne",
        "kassemedarbejder",
        "kassemedearbejderen",
        "kassemedarbejdere",
        "kassemedarbejderne",
        "kok",
        "kokken",
        "kokke",
        "kokkene",
        "kemiker",
        "kemikeren",
        "kemikere",
        "kemikerne",
        "chef",
        "chefen",
        "chefer",
        "cheferne",
        "rengøringshjælp",
        "rengøringshjælpen",
        "rengøringshjælpere",
        "rengøringshjælperne",
        "ekspedient",
        "ekspedienten",
        "ekspedienter",
        "ekspedienterne",
        "terapeut",
        "terapeuten",
        "terapeuter",
        "terapeuterne",
        "advokat",
        "advokaten",
        "advokater",
        "advokaterne",
        "diætist",
        "diætisten",
        "diætister",
        "diætisterne",
        "læge",
        "lægen",
        "læger",
        "lægerne",
        "chauffør",
        "chaufføren",
        "chauffører",
        "chaufførerne",
        "redaktør",
        "redatøren",
        "redaktører",
        "redaktørerne",
        "elektriker",
        "elektrikeren",
        "elektrikere",
        "elektrikerne",
        "ingeniør",
        "ingeniøren",
        "ingeniører",
        "ingeniørerne",
        "landmand",
        "landmanden",
        "landmænd",
        "landmændene",
        "brandmand",
        "brandmanden",
        "brandmænd",
        "brandmændene",
        "vagt",
        "vagten",
        "vagter",
        "vagterne",
        "frisør",
        "frisøren",
        "frisører",
        "frisørerne",
        "instruktør",
        "instruktøren",
        "instruktører",
        "instruktørerne",
        "efterforsker",
        "efterforskeren",
        "efterforskere",
        "efterforskerne",
        "pedel",
        "pedellen",
        "pedeller",
        "pedellerne",
        "advokat",
        "advokaten",
        "advokater",
        "advokaterne",
        "bibliotekar",
        "bibliotekaren",
        "bibliotekarer",
        "bibliotekarerne",
        "mekaniker",
        "makanikeren",
        "mekanikere",
        "mekanikerne",
        "sygeplejerske",
        "sygeplersken",
        "sygeplejersker",
        "sygeplejeskerne",
        "politibetjent",
        "politibetjenten",
        "politibetjente",
        "politibetjentene",
        "maler",
        "maleren",
        "malerne",
        "malere",
        "ambulanceredder",
        "ambulanceredderen",
        "ambulancereddere",
        "ambulanceredderne",
        "ambulancebehandler",
        "ambulancebehandleren",
        "ambulancebehandlere",
        "ambulancebehandlerne",
        "patolog",
        "patologen",
        "patologer",
        "patologerne",
        "farmaceut",
        "farmaceuten",
        "farmaceuter",
        "farmaceuterne",
        "blikkenslager",
        "blikkenslageren",
        "blikkenslagere",
        "blikkenslagerne",
        "programmør",
        "programmøren",
        "programmører",
        "programmørerne",
        "psykolog",
        "psykologen",
        "psykologer",
        "psykologerne",
        "receptionist",
        "receptionisten",
        "receptionister",
        "receptionisterne",
        "sekretær",
        "sekretæren",
        "sekretærer",
        "sekretærerne",
        "kirurg",
        "kirurgen",
        "kirurger",
        "kirurgerne",
        "skrædder",
        "skrædderen",
        "skræddere",
        "skrædderne",
        "tekniker",
        "teknikeren",
        "teknikere",
        "teknikerne",
        "terapeut",
        "terapeuten",
        "terapeuter",
        "terapeuterne",
        "dyrlæge",
        "dyrlægen",
        "dyrlæger",
        "dyrlægerne",
        "forfatter",
        "forfatteren",
        "forfattere",
        "forfatterne",
    ]
)

female_gendered_terms = set(
    [
        "pige",
        "pigen",
        "piger",
        "pigerne",
        "søster",
        "søsteren",
        "søstere",
        "søsterne",
        "mor",
        "moren",
        "mødre",
        "mødrene",
        "kone",
        "konen",
        "koner",
        "konerne",
        "brud",
        "bruden",
        "brude",
        "brudene",
        "dame",
        "damen",
        "damer",
        "damerne",
        "datter",
        "datteren",
        "døtre",
        "døtrene",
    ]
)

male_gendered_terms = set(
    [
        "dreng",
        "drengen",
        "drenge",
        "drengene",
        "bror",
        "broren",
        "brødre",
        "brødrene",
        "far",
        "faren",
        "fædre",
        "fædrene",
        "mand",
        "manden",
        "mænd",
        "mændene",
        "brudgom",
        "brudgommen",
        "brudgomme",
        "brudgommene",
        "herre",
        "herren",
        "herrer",
        "herrerne",
        "søn",
        "sønnen",
        "sønner",
        "sønnerne",
    ]
)

danish_adult_words = set(
    [
        "amatør",
        "anal",
        "anus",
        "babes",
        "bdsm",
        "begær",
        "bestialitet",
        "blodig",
        "blowjob",
        "bordel",
        "bordeller",
        "bryster",
        "bøsse",
        "bøssefilm",
        "c-skål",
        "damer",
        "dating",
        "dildo",
        "dildoer",
        "dildomaskine",
        "dyrisk",
        "ejakulation",
        "ejakulere",
        "ejakulerede",
        "ejakulerer",
        "elskerinde",
        "endetarm",
        "erotik",
        "erotisk",
        "erotiske",
        "escort",
        "escortpige",
        "escortpiger",
        "escortpigerne",
        "fanden",
        "fisse",
        "fisser",
        "fræk",
        "frække",
        "frækt",
        "fucked",
        "fucker",
        "gangbang",
        "gay",
        "hardcore",
        "hentai",
        "homo",
        "hore",
        "intim",
        "intime",
        "kinky",
        "klitoris",
        "kneppe",
        "kusse",
        "kvinder",
        "latex",
        "latino",
        "lesbisk",
        "liderlig",
        "liderlige",
        "lort",
        "lorte",
        "luder",
        "masochist",
        "massage",
        "massageescort",
        "massageklinik",
        "massagen",
        "massagepige",
        "massagepiger",
        "massagepigerne",
        "milf",
        "nigger",
        "niggere",
        "nøgenbillede",
        "nøgenbilleder",
        "nøgenbillederne",
        "nøgne",
        "onanere",
        "orgasme",
        "orgasmer",
        "patter",
        "pecker",
        "penis",
        "piger",
        "pigesex",
        "pik",
        "pis",
        "pisse",
        "pisser",
        "pisses",
        "porn",
        "porno",
        "porno-casting",
        "pornofilm",
        "pornografi",
        "pornostar",
        "pornostjerne",
        "pornostjernen",
        "pornostjerner",
        "prostitueret",
        "røv",
        "røvhul",
        "røvhuller",
        "sadist",
        "samleje",
        "sex",
        "sexcam",
        "sexdating",
        "sexdatingsites",
        "sexfilm",
        "sexfoto",
        "sexhistorier",
        "sexparadis",
        "sexshop",
        "sexstillinger",
        "sexvideo",
        "sexvideoer",
        "sexvideoerne",
        "sexvideoen",
        "sexy",
        "shemale",
        "shemales",
        "sjofelhed",
        "sjofelheder",
        "sjofelhederne",
        "skamlæber",
        "skider",
        "sluger",
        "sm",
        "spanking",
        "sprække",
        "sprøjteorgasme",
        "sprøjteorgasmer",
        "sprøjteorgasmen",
        "sprøjteorgasmerne",
        "strip",
        "svans",
        "swinger",
        "swingerdating",
        "swingerklub",
        "sæd",
        "sædafgang",
        "tantra",
        "telefonsex",
        "testikel",
        "thai",
        "thaimassage",
        "thaipiger",
        "tranny",
        "tæve",
        "tæver",
        "tøs",
        "tøser",
        "urin",
        "vagina",
        "vaginaen",
        "viagra",
        "viagraen",
        "voldtage",
        "voldtager",
        "voldtægt" "vulva",
        "webcam",
        "webcam-chat",
        "x-bedømt",
        "xxx",
    ]
)


def get_muslim_name_patterns() -> List[Dict[str, list]]:
    """Gets a list of all muslim first names in Denmark from DaCy, and converts to a list of lowercase spacy patterns.

    Returns:
        List[Dict[str, list]]: list of lowercase spacy match patterns
    """
    from dfm.description.match_counter import MatchCounter
    from dacy.datasets import muslim_names

    muslim_names_list = [name.lower() for name in muslim_names()["first_name"]]

    return MatchCounter.term_list_to_spacy_match_patterns(
        term_list=muslim_names_list, label="muslim_names"
    )


def get_gender_name_patterns() -> List[Dict[str, list]]:
    """Gets a list of all gendered first names in Denmark from DaCy, and converts to a list of lowercase spacy patterns.

    Returns:
        List[Dict[str, list]]: list of lowercase spacy match patterns
    """
    from dacy.datasets import female_names, male_names
    from dfm.description.match_counter import MatchCounter

    female_names_list = [name.lower() for name in female_names()["first_name"]]
    female_names_patterns = MatchCounter.term_list_to_spacy_match_patterns(
        female_names_list, label="female_names"
    )

    male_names_list = [name.lower() for name in male_names()["first_name"]]
    male_name_patterns = MatchCounter.term_list_to_spacy_match_patterns(
        male_names_list, label="male_names"
    )

    return female_names_patterns + male_name_patterns
