"""
This type stub file was generated by pyright.
"""

valid_lang_ids = ...

def test(predictions, labels, k=...):  # -> tuple[float, float]:
    """
    Return precision and recall modeled after fasttext's test
    """
    ...

def find_nearest_neighbor(query, vectors, ban_set, cossims=...):  # -> Any:
    """
    query is a 1d numpy array corresponding to the vector to which you want to
    find the closest vector
    vectors is a 2d numpy array corresponding to the vectors you want to consider
    ban_set is a set of indicies within vectors you want to ignore for nearest match
    cossims is a 1d numpy array of size len(vectors), which can be passed for efficiency

    returns the index of the closest match to query within vectors

    """
    ...

def reduce_model(ft_model, target_dim):
    """
    ft_model is an instance of `_FastText` class
    This function computes the PCA of the input and the output matrices
    and sets the reduced ones.
    """
    ...

def download_model(lang_id, if_exists=..., dimension=...):  # -> None:
    """
    Download pre-trained common-crawl vectors from fastText's website
    https://fasttext.cc/docs/en/crawl-vectors.html
    """
    ...
