streams:
    - name: munin_alpha_v0.1_zero_cleaned
      documents:
        - /work/dfm-data/pre-training/dagw/documents/*.gz
        - /work/dfm-data/pre-training/hplt/documents/*.gz
        - /work/dfm-data/pre-training/lexdk/documents/*.gz
        - /work/dfm-data/pre-training/mC4_da/documents/*.gz
        - /work/dfm-data/pre-training/scandi-reddit/documents/*.gz
      output:
        path: /work/dfm-data/pre-training-clean/2024-v1/documents
        max_size_in_bytes: 1_000_000_000
      attributes:
        - v1blockurltaggers
        - bff_duplicate_paragraph_spans
      filter:
        # Remove documents that are in the utp domain blocklist
        exclude:
            - "$@.attributes[?(@.v1blockurltaggers__domain_blocklist_utp_v1__url && @.v1blockurltaggers__domain_blocklist_utp_v1__url[0] && @.v1blockurltaggers__domain_blocklist_utp_v1__url[0][2] >=1.0)]"
      # Replace duplicate lines with empty string
      span_replacement:
        - span: "$.attributes.bff_duplicate_paragraph_spans"
          min_score: 0.5
          replacement: ''

processes: 16
