"""
This type stub file was generated by pyright.
"""

from __future__ import absolute_import, division, print_function, unicode_literals
from .FastText import (
    BOW,
    EOS,
    EOW,
    cbow,
    load_model,
    skipgram,
    supervised,
    tokenize,
    train_supervised,
    train_unsupervised,
)
