occupation_pattern_list = [
    "revisor", "revisoren", "revisorer", "revisorerne",
    "administrator", "administratoren", "administratorer", "administratorerne",
    "analytiker", "analytikeren", "analytikere", "analytikerne",
    "arkitekt", "arkitekten", "arkitekter", "arkitekterne",
    "assistent", "assistenten", "assistenter", "assistenterne",
    "bager", "bageren", "bagere", "bagerne",
    "bartender", "bartenderen", "bartendere", "bartenderne",
    "ejendomsmægler", "ejendomsmægleren", "ejendomsmæglere", "ejendomsmæglerne"
    "tømrer", "tømreren", "tømrere", "tømrerne",
    "kassemedarbejder", "kassemedearbejderen", "kassemedarbejdere", "kassemedarbejderne",
    "kok", "kokken", "kokke", "kokkene",
    "kemiker", "kemikeren", "kemikere", "kemikerne",
    "chef", "chefen", "chefer", "cheferne",
    "rengøringshjælp", "rengøringshjælpen", "rengøringshjælpere", "rengøringshjælperne",
    "ekspedient", "ekspedienten", "ekspedienter", "ekspedienterne",
    "terapeut", "terapeuten", "terapeuter", "terapeuterne",
    "advokat", "advokaten", "advokater", "advokaterne",
    "diætist", "diætisten", "diætister", "diætisterne", 
    "læge", "lægen", "læger", "lægerne",
    "chauffør", "chaufføren", "chauffører", "chaufførerne",
    "redaktør", "redatøren", "redaktører", "redaktørerne",
    "elektriker", "elektrikeren", "elektrikere", "elektrikerne",
    "ingeniør", "ingeniøren", "ingeniører", "ingeniørerne",
    "landmand", "landmanden", "landmænd", "landmændene",
    "brandmand", "brandmanden", "brandmænd", "brandmændene",
    "vagt", "vagten", "vagter", "vagterne",
    "frisør", "frisøren", "frisører", "frisørerne",
    "instruktør", "instruktøren", "instruktører", "instruktørerne",
    "efterforsker", "efterforskeren", "efterforskere", "efterforskerne",
    "pedel", "pedellen", "pedeller", "pedellerne",
    "advokat", "advokaten", "advokater", "advokaterne",
    "bibliotekar", "bibliotekaren", "bibliotekarer", "bibliotekarerne",
    "mekaniker", "makanikeren", "mekanikere", "mekanikerne",
    "sygeplejerske", "sygeplersken", "sygeplejersker", "sygeplejeskerne",
    "politibetjent", "politibetjenten", "politibetjente", "politibetjentene",
    "maler", "maleren", "malerne", "malere",
    "ambulanceredder", "ambulanceredderen", "ambulancereddere", "ambulanceredderne", 
    "ambulancebehandler", "ambulancebehandleren", "ambulancebehandlere", "ambulancebehandlerne",
    "patolog", "patologen", "patologer", "patologerne",
    "farmaceut", "farmaceuten", "farmaceuter", "farmaceuterne",
    "blikkenslager", "blikkenslageren", "blikkenslagere", "blikkenslagerne",
    "programmør", "programmøren", "programmører", "programmørerne",
    "psykolog", "psykologen", "psykologer", "psykologerne"
    "receptionist", "receptionisten", "receptionister", "receptionisterne",
    "sekretær", "sekretæren", "sekretærer", "sekretærerne",
    "kirurg", "kirurgen", "kirurger", "kirurgerne",
    "skrædder", "skrædderen", "skræddere", "skrædderne",
    "tekniker", "teknikeren", "teknikere", "teknikerne",
    "terapeut", "terapeuten", "terapeuter", "terapeuterne",
    "dyrlæge", "dyrlægen", "dyrlæger", "dyrlægerne",
    "forfatter", "foraftteren", "forfattere", "forfatterne"
]

female_gendered_terms = [
    "pige", "pigen", "piger", "pigerne",
    "søster", "søsteren", "søstere", "søsterne",
    "mor", "moren", "mødre", "mødrene",
    "kone", "konen", "koner", "konerne",
    "brud", "bruden", "brude", "brudene",
    "dame", "damen", "damer", "damerne",
    "datter", "datteren", "døtre", "døtrene"
]

male_gendered_terms = [
    "dreng", "drengen", "drenge", "drengene",
    "bror", "broren", "brødre", "brødrene",
    "far", "faren", "fædre", "fædrene",
    "mand", "manden", "mænd", "mændene", 
    "brudgom", "brudgommen", "brudgomme", "brudgommene",
    "herre", "herren", "herrer", "herrerne",
    "søn", "sønnen", "sønner", "sønnerne"
]
