name: 'lint and build dev container' 
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main


jobs:
  build:
    concurrency:
      group: "${{ github.workflow }} @ ${{ github.ref }}"
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/centre-for-humanities-computing/danish-foundation-models-devcontainer:latest
          cacheFrom: ghcr.io/centre-for-humanities-computing/danish-foundation-models-devcontainer:latest
          push: filter
          refFilterForPush: refs/heads/main
          runCmd:
            make lint